package com.nas.alreem.constants

import com.nas.alreem.activity.survey.model.SurveySubmitDataModel

class ConstantWords {
    companion object
    {
        var emailHelp:String="communications@alreem.com"
        var status_101="Some Error Occured."
        var status_102="Internal Server Error."
        var status_103="Validation Error."
        var status_110="Invalid username and password."
        var status_118="Invalid username and password."
        var status_113="Verification code not match."
        var status_114="This Email ID is not registered with our school. Kindly enter the school registered Email ID."
        var status_116="Token expired."
        var status_123="Invalid file access."
        var status_124="Route not found."
        var status_125="Student not found in our database."
        var status_130="DecryptException Error."
        var status_131="Url/Method not found."
        var status_132="No Data Found."
        var status_133="Restricted access."
        var status_134="Method Not Allowed."
        var status_135="User not triggered."
        var status_121="The Email ID is already Registered."
        var status_510="Too many login attempts.Please try After 1 minute."
        var status_111="No Students are linked with this Email ID."
        var status_100_signup="Successfully registered.Please check your email for further details."
        var status_100_forget_password="New Password has send to your Email Id.Please check your email for further details."
        var status_100_login="Successfully Logged in."
        var status_100_change_password="Successfully Reset your password."
        var no_notification_found="No Notification Found."
var status_141="Please Submit Before 2 pm"


        /*TAB_ID*/
        var TAB_STUDENT_INFORMATION = "1"
        var TAB_NOTIFICATIONS = "2"
        var TAB_CALENDAR = "3"
        var TAB_COMMUNICATION = "4"
        var TAB_PAYMENTS = "5"
        var TAB_REENROLMENT = "10"
        var TAB_LUNCH_BOX = "7"
        var TAB_SHOP="8"
        var TAB_PARENT_ESSENTIAL = "9"
        var TAB_ABSENCE = "6"
        var TAB_EARLY_YEARS = "11"
        var TAB_PRIMARY = "12"
        var TAB_SECONDARY = "13"
        var TAB_PERFORMINGARTS = "14"
        //var TAB_BUS_SERVICE="12"
       //var TAB_INTENTIONS="13"
        var TAB_REPORTS = "15"
        //var TAB_TIMETABLE = "15"
        var TAB_PERMISSION_FORMS = "16"
        var TAB_ENRICHMENT = "17"
       // var TAB_PARENT_ASSOCIATION = "18"
        var TAB_PARENT_MEETINGS = "18"
        var TAB_GALLERY = "19"
        var TAB_CONTACT_US = "20"
        var TAB_ABOUT_US = "21"





        /*MODULE NAME*/
        var notification="Notifications"
        var calendar="Calendar"
        var payments="Payments"
        var early_years="Early Years"
        var primary="Primary"
        var secondary="Secondary"
        var gallery="Gallery"
        var about_us="About Us"
        var contact_us="Contact Us"
        var settings="Settings"
        var lunchbox="Lunch Box"
        var communications="Communications"
        var busservice = "Bus Service"
        var intention= "Intentions"
        var performingarts="Performing Arts"
        var timetable ="Timetable"
        var shop = "Shop"
        var social_media="Social Media"
        var information="Informations"
        var studentinformation ="Student Information"
        var newsletters="Newsletters"
        var parentessential="Parent Essentials"
        var parentmeetings="Parent Meetings"
        var absence_earlypickup="Absence & Early Pickup"
        var bus_service = "Bus Service"
        var enrichment = "Enrichment"
        var permission_forms="Forms"
        var reenrollment = "Re-Enrolment"
        var parentassociation = "Parent Engagement"
        var absence="Absence"
        var earlypickup="Early Pickup"
        var staff_directory="Staff Directory"
        var reports="Reports"

        var surveySubmitArrayList=ArrayList<SurveySubmitDataModel>()
    }
}